spring.application.name=gestao-tarefas

spring.datasource.url = jdbc:postgresql://localhost:5432/gestao-tarefas
spring.datasource.username=postgres
spring.datasource.password=1234

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration